/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      screens: {
        ms: "360px",
        lg2: "1024px",
        lg: "1220px",
        hoverable: { raw: "(hover: hover)" },
      },
      colors: {
        primary: "#FF6998",
        "primary-light": "#FFF3F3",
        peach: "#FF91A5",
        "peach-light": "#FFF2ED",
        "pink-1": "#FFC0F1",
        purple: "#B988F7",
        "purple-light": "#F1F5FE",
        "purple-1": "#6361FF",
        indigo: "#4C73DA",
        "indigo-light": "#F1F8FF",
        sky: "#55CDF2",
        "sky-light": "#E4F8FB",
        "sky-1": "#5DD7FF",
        orange: "#FEA735",
        "orange-light": "#FFFBD6",
        "orange-1": "#FF8945",
        green: "#36CBA6",
        "green-light": "#EDFBF9",
        "green-1": "#B5EED3",
        "gray-1": "#1E2432",
        "gray-2": "#4A4E57",
        "gray-3": "#6A6D75",
        "gray-4": "#CFCFD6",
        "gray-5": "#DFDFE8",
        "gray-6": "#F5F7FA",
        "gray-7": "#C7CAD1",
        "yellow-1": "#FFD488",
        "yellow-2": "#FFDA2A",
        white: "#FFFFFF",
        black: "#000000",
        red: "#FC6E51",
      },
      fontSize: {
        "fz-1": ["4rem", "5.625rem"],
        "fz-2": ["3.5rem", "5rem"],
        "fz-3": ["3rem", "4.375rem"],
        "fz-4": ["2rem", "3.375rem"],
        "fz-5": ["1.5rem", "2.375rem"],
        "fz-6": ["1.25rem", "2.125rem"],
        "fz-7": ["1.125rem", "2rem"],
        "fz-8": ["1rem", "1.75rem"],
        // mobile
        "fz-1-mobile-text": ["2.375rem", "3.5rem"],
        "fz-1-mobile-number": ["3rem", "4rem"],
        "fz-2-mobile-text": ["2rem", "3rem"],
        "fz-2-mobile-number": ["2.5rem", "3.625rem"],
        "fz-3-mobile": ["1.75rem", "2.75rem"],
        "fz-4-mobile": ["1.375rem", "2.25rem"],
        "fz-5-mobile": ["1.125rem", "2rem"],
        "fz-6-mobile": ["1rem", "1.75rem"],
        "fz-7-mobile": ["1rem", "1.75rem"],
        "fz-8-mobile": ["0.875rem", "1.375rem"],
      },
      spacing: {
        stretch: "stretch",
        15: "3.75rem",
        130: "32.5rem",
      },
    },
  },
  plugins: [],
};
