import "./globals.css";
import { Metadata } from "next";

import { Noto_Sans_TC } from "next/font/google";

const inter = Noto_Sans_TC({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
    googleBot: {
      index: false,
      follow: false,
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang={"en"}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
